version: '3'

services:
  aws:
    image: amazon/aws-cli:latest
    volumes:
      - aws_dir:/root/.aws
  sam:
    image: public.ecr.aws/sam/build-python3.8:1.52.0
    command: sam
    volumes:
      - aws_dir:/root/.aws

volumes:
  aws_dir:
